[package]
name = "smolser-derive"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0", default-features = false }
quote = { version = "1.0", default-features = false }
syn = { version = "2.0", default-features = false, features = [
  "derive", "parsing", "printing", "proc-macro"
] }

[dev-dependencies]
smolser = { path = "../smolser" }
trybuild = { version = "1.0", default-features = false }
